version: '3.7'
services:

  # PHP Service
  hhtest_app:
    container_name: hhtest_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    tty: true
    env_file: .env
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/dev/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/dev/cacert.pem:/usr/curl/certs/cacert.pem
    networks:
      - hhtest-network

  # Nginx Service
  hhtest_webserver:
    container_name: hhtest_webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/certs/:/etc/nginx/certs/
    networks:
      - hhtest-network

  # MySQL Service
  hhtest_db:
    container_name: hhtest_db
    image: library/mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3381:3306"
    env_file: .env
    volumes:
      - hhtest_mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - hhtest-network

  # Node service
  hhtest_node:
    container_name: hhtest_node
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www

  # Redis
  hhtest_redis:
    image: 'redis:alpine'
    container_name: hhtest_redis
    ports:
      - '6379:6379'
    volumes:
      - 'hhtest_redis_data:/data'
    networks:
      - hhtest-network

# Project volumes
volumes:
  hhtest_mysql_data:
    driver: local
  hhtest_redis_data:
    driver: local

# Docker Networks
networks:
  hhtest-network:
    driver: bridge
